version: '3'
services:
  web:
    image: python:3.10
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./menu:/app/menu
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: sqlite
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
